export const data = [
  {
    id: 1,
    titulo: 'El Señor de los Anillos',
    autor: 'J.R.R. Tolkien',
    año: 1954,
    genero: 'Fantasía',
    paginas: 1216,
    isbn: '978-0618640157',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
    preselected: true,
  },
  {
    id: 2,
    titulo: 'Cien Años de Soledad',
    autor: 'Gabriel García Márquez',
    año: 1967,
    genero: 'Realismo Mágico',
    paginas: 417,
    isbn: '978-0307389732',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
    defaultExpanded: true,
  },
  {
    id: 3,
    titulo: '1984',
    autor: 'George Orwell',
    año: 1949,
    genero: 'Ciencia Ficción',
    paginas: 328,
    isbn: '978-0451524935',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
    status: 'disabled',
    defaultExpanded: true,
  },
  {
    id: 4,
    titulo: 'Orgullo y Prejuicio',
    autor: 'Jane Austen',
    año: 1813,
    genero: 'Romántico',
    paginas: 279,
    isbn: '978-1503290563',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
    disabledExpanded: true,
  },
  {
    id: 5,
    titulo: 'El Gran Gatsby',
    autor: 'F. Scott Fitzgerald',
    año: 1925,
    genero: 'Clásico',
    paginas: 180,
    isbn: '978-0743273565',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
    status: 'disabled',
  },
  {
    id: 6,
    titulo: 'Matar a un Ruiseñor',
    autor: 'Harper Lee',
    año: 1960,
    genero: 'Drama',
    paginas: 281,
    isbn: '978-0061120084',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
    disabledExpanded: true,
  },
  {
    id: 7,
    titulo: 'Crimen y Castigo',
    autor: 'Fiódor Dostoyevski',
    año: 1866,
    genero: 'Filosófico',
    paginas: 671,
    isbn: '978-0486415871',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
    preselected: true,
  },
  {
    id: 8,
    titulo: 'Don Quijote de la Mancha',
    autor: 'Miguel de Cervantes',
    año: 1605,
    genero: 'Aventura',
    paginas: 863,
    isbn: '978-8491050641',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
  },
  {
    id: 9,
    titulo: 'La Metamorfosis',
    autor: 'Franz Kafka',
    año: 1915,
    genero: 'Ficción',
    paginas: 201,
    isbn: '978-0486290300',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
    status: 'disabled',
  },
  {
    id: 10,
    titulo: 'En Busca del Tiempo Perdido',
    autor: 'Marcel Proust',
    año: 1913,
    genero: 'Modernismo',
    paginas: 4215,
    isbn: '978-2070111080',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
    preselected: true,
  },
  {
    id: 11,
    titulo: 'Ulises',
    autor: 'James Joyce',
    año: 1922,
    genero: 'Modernismo',
    paginas: 730,
    isbn: '978-0199535675',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
  },
  {
    id: 12,
    titulo: 'El Nombre de la Rosa',
    autor: 'Umberto Eco',
    año: 1980,
    genero: 'Misterio',
    paginas: 512,
    isbn: '978-0156001311',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
  },
  {
    id: 13,
    titulo: 'Rayuela',
    autor: 'Julio Cortázar',
    año: 1963,
    genero: 'Ficción',
    paginas: 736,
    isbn: '978-8432230851',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
  },
  {
    id: 14,
    titulo: 'Los Miserables',
    autor: 'Victor Hugo',
    año: 1862,
    genero: 'Histórico',
    paginas: 1463,
    isbn: '978-0451419439',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
  },
  {
    id: 15,
    titulo: 'La Odisea',
    autor: 'Homero',
    año: -800,
    genero: 'Épico',
    paginas: 541,
    isbn: '978-0140268867',
    sinopsis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas placerat felis dui, a tincidunt risus maximus sit amet. In ut tempor turpis, ac vulputate nunc. Mauris pharetra libero pulvinar arcu imperdiet, ac scelerisque lectus egestas. Suspendisse in aliquet neque. Curabitur dignissim pretium neque. Curabitur eu metus in leo cursus congue. Phasellus scelerisque tristique fermentum. In aliquet porttitor sodales. ',
  },
]
